Adding logout functionality.
dakkusingh/openam_api pull request #2
Opened 2019-02-01 09:24 UTC by kshamadeshmukh

2019-02-01 09:37 UTC, dakkusingh requested changes

2019-02-01 09:37 UTC, dakkusingh commented on src/Service/Users.php
> +      $apiOptions['uri_template_options'] = array();
Short array syntax

2019-02-01 09:37 UTC, dakkusingh commented on src/Service/Users.php
> +   * @return bool|mixed|null|\Psr\Http\Message\StreamInterface
not sure if this return makes sense?

2019-02-02 22:36 UTC, dakkusingh commented
@passionatepoorna are you able to make minor amends to this too so we can merge this also?

2019-02-02 23:44 UTC, snwalkunde commented on src/Service/Users.php
> +      $apiOptions['uri_template_options'] = array();
Done

2019-02-02 23:44 UTC, snwalkunde commented on src/Service/Users.php
> +   * @return bool|mixed|null|\Psr\Http\Message\StreamInterface
Updated the `@return`

2019-02-03 08:57 UTC, merged